version: '3.8'

services:
  vision_node:
    image: web-vision-pro:1.0
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: paper_vision_node
    privileged: true  # Required for hardware access (cameras)
    network_mode: "host" # Required for GigE cameras discovery
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PYLON_CAMEMU=2
      - PYLON_ROOT=/opt/pylon
      - LD_LIBRARY_PATH=/opt/pylon/lib:$LD_LIBRARY_PATH
      - QT_DEBUG_PLUGINS=1
    volumes:
      - ../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../data:/app/data
    working_dir: /app
    command: /bin/bash -c "mkdir -p build && cd build && cmake .. && make && ./PaperVision_App"
    stdin_open: true
    tty: true
