version: '3.8'

services:
  vision_node:
    image: web-vision-pro:1.0
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: paper_vision_node
    privileged: true  # Required for hardware access (cameras)
    network_mode: "host" # Required for GigE cameras discovery
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PYLON_ROOT=/opt/pylon
      - LD_LIBRARY_PATH=/opt/pylon/lib:$LD_LIBRARY_PATH
    volumes:
      - ../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app
    command: /bin/bash -lc "mkdir -p /app/build && cd /app/build && cmake .. && cmake --build . --target PaperVision_App -- -j$(nproc) && chmod 755 /app/build/PaperVision_App && /app/build/PaperVision_App"
    stdin_open: true
    tty: true
